"""
Apollo View - Streamlit application.
Single-file UI with four pages managed via session_state["page"].
"""

import time
import traceback
from datetime import date

import streamlit as st


st.set_page_config(
    layout="wide",
    page_title="Apollo View",
    page_icon="\U0001f52d",
)

# ---------------------------------------------------------------------------
# Branding
# ---------------------------------------------------------------------------

ACCENT = "#5B2C8B"
ACCENT_LIGHT = "#7B4FAD"
ACCENT_BG = "#f5f0fa"

AI_DISCLAIMER = (
    "This briefing was generated by AI and may contain errors or omissions. "
    "All content should be independently verified before use in any "
    "investment decision or client interaction."
)

DISCLAIMER_HTML = (
    f'<div style="padding:10px 16px; margin-top:24px; border-radius:6px; '
    f'background:{ACCENT_BG}; border-left:3px solid {ACCENT}; '
    f'font-size:11px; color:#444; line-height:1.5;">'
    f'<strong>AI-Generated Content</strong> &mdash; {AI_DISCLAIMER}</div>'
)


def render_disclaimer():
    st.markdown(DISCLAIMER_HTML, unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Report template
# ---------------------------------------------------------------------------

REPORT_TEMPLATE = {
    "report_name": "Investment Manager Meeting Briefing",
    "default_sections": [
        {
            "title": "Executive Summary",
            "purpose": "Summarize the most important issues for the meeting.",
            "preferred_data_sources": ["structured", "rag", "market", "news"],
        },
        {
            "title": "Client / Plan Overview",
            "purpose": "Describe the pension plan, its scale, constraints, and strategic context.",
            "preferred_data_sources": ["structured", "rag"],
        },
        {
            "title": "Relationship Context",
            "purpose": "Summarize relationship history, prior interactions, and relevant board sentiment.",
            "preferred_data_sources": ["structured", "rag"],
        },
        {
            "title": "Strategy Context",
            "purpose": "Explain the strategy-specific market and portfolio context relevant to the meeting.",
            "preferred_data_sources": ["market", "news", "structured"],
        },
        {
            "title": "Risks and Pressure Points",
            "purpose": "Highlight concerns, conflicts, scrutiny points, and unresolved issues.",
            "preferred_data_sources": ["structured", "rag", "market", "news"],
        },
        {
            "title": "Recommended Talking Points",
            "purpose": "Provide practical talking points and guidance for the meeting.",
            "preferred_data_sources": ["structured", "rag", "market", "news"],
        },
    ],
    "optional_sections": [
        {
            "title": "Competitive Landscape",
            "purpose": "Compare competitors and likely differentiation points.",
            "preferred_data_sources": ["structured", "market", "news"],
        },
        {
            "title": "RFP / Mandate Requirements",
            "purpose": "Summarize requirements, evaluation criteria, and mandate expectations.",
            "preferred_data_sources": ["rag", "structured"],
        },
        {
            "title": "Board Dynamics",
            "purpose": "Summarize decision-makers, known priorities, and likely question patterns.",
            "preferred_data_sources": ["structured", "rag"],
        },
        {
            "title": "Upcoming Dates and Decision Timeline",
            "purpose": "Highlight key dates, deadlines, renewals, and timing risks.",
            "preferred_data_sources": ["structured"],
        },
    ],
}


# ---------------------------------------------------------------------------
# Cached agent initialization
# ---------------------------------------------------------------------------

@st.cache_resource
def get_decomposition_agent():
    from agent_01_query_decomposition import QueryDecompositionAgent
    return QueryDecompositionAgent()


@st.cache_resource
def get_structured_agent():
    from agent_02_structured_data import StructuredDataAgent
    return StructuredDataAgent()


@st.cache_resource
def get_rag_agent():
    from agent_03_document_rag import DocumentRAGAgent
    return DocumentRAGAgent()


@st.cache_resource
def get_market_agent():
    from agent_04_market_intelligence import MarketIntelAgent
    return MarketIntelAgent()


@st.cache_resource
def get_news_agent():
    from agent_05_news import NewsAgent
    return NewsAgent(mock_mode=False)


@st.cache_resource
def get_synthesis_agent():
    from agent_06_synthesis import SynthesisAgent
    return SynthesisAgent()


# ---------------------------------------------------------------------------
# Navigation
# ---------------------------------------------------------------------------

def go_to(page: str):
    st.session_state["page"] = page


# ---------------------------------------------------------------------------
# PAGE 1 - Input
# ---------------------------------------------------------------------------

def page_input():
    st.title("\U0001f52d Apollo View")
    st.caption("AI-Powered Meeting Intelligence")
    st.markdown("---")

    col1, col2 = st.columns(2)

    with col1:
        plan_name = st.text_input("Plan Name", value="CalPERS", help="e.g. CalPERS, CalSTRS")
        strategy = st.text_input("Strategy", value="Core Fixed Income")
        meeting_type = st.selectbox(
            "Meeting Type",
            ["Annual Review", "RFP Finalist", "First Introduction"],
        )

    with col2:
        meeting_date = st.date_input("Meeting Date", value=date.today())
        manager_name = st.text_input("Manager Name (optional)", value="")
        additional_notes = st.text_area("Additional Notes (optional)", value="", height=100)

    st.markdown("---")

    if st.button("Generate Briefing", type="primary", use_container_width=True):
        if not plan_name.strip():
            st.error("Plan Name is required.")
            return
        if not strategy.strip():
            st.error("Strategy is required.")
            return

        st.session_state["input"] = {
            "plan_name": plan_name.strip(),
            "strategy": strategy.strip(),
            "meeting_type": meeting_type,
            "meeting_date": str(meeting_date),
            "manager_name": manager_name.strip() or None,
            "additional_notes": additional_notes.strip() or None,
        }
        go_to("progress")
        st.rerun()

    render_disclaimer()


# ---------------------------------------------------------------------------
# PAGE 2 - Progress
# ---------------------------------------------------------------------------

STEP_DESCRIPTIONS = {
    "decomposition": "Understanding your meeting and figuring out what to research...",
    "structured": "Pulling fund performance, fees, contract dates, and board info from the database...",
    "rag": "Reading through documents, board minutes, and past meeting notes...",
    "market": "Reviewing the latest market research on fixed income...",
    "news": "Searching for the latest news about this plan and strategy...",
    "synthesis": "Writing your briefing -- this takes a minute, drafting each section...",
}

# Typical seconds per step (used for time-remaining estimate)
STEP_EST_SECONDS = {
    "decomposition": 15,
    "structured": 30,
    "rag": 25,
    "market": 25,
    "news": 10,
    "synthesis": 120,
}

# Ordered step keys matching the pipeline order
STEP_ORDER = ["decomposition", "structured", "rag", "market", "news", "synthesis"]


def _build_step_html(label: str, detail: str) -> str:
    """One completed step as styled HTML."""
    detail_span = f'<span style="color:#666;"> &mdash; {detail}</span>' if detail else ""
    return (
        f'<div style="padding:6px 0; font-size:14px;">'
        f'<span style="color:{ACCENT}; font-weight:600;">{label}</span>'
        f'{detail_span}'
        f'</div>'
    )


def _format_remaining(seconds: float) -> str:
    seconds = max(0, int(seconds))
    if seconds >= 60:
        m, s = divmod(seconds, 60)
        return f"~{m}m {s}s remaining"
    return f"~{seconds}s remaining"


def page_progress():
    from agent_01_query_decomposition import MeetingContext

    inp = st.session_state.get("input")
    if not inp:
        go_to("input")
        st.rerun()
        return

    context = MeetingContext(**inp)

    st.title("\U0001f52d Apollo View")
    st.markdown(
        f"Preparing your briefing for **{context.plan_name}** \u00b7 "
        f"*{context.strategy}* \u00b7 {context.meeting_type}"
    )
    st.markdown("---")

    progress_bar = st.progress(0)
    time_placeholder = st.empty()
    status_placeholder = st.empty()
    log_placeholder = st.empty()

    completed_html_parts: list[str] = []
    total_est = sum(STEP_EST_SECONDS.values())
    elapsed_total = 0.0

    def update_time_remaining():
        remaining = max(0, total_est - elapsed_total)
        time_placeholder.markdown(
            f'<div style="font-size:13px; color:#888; padding:4px 0;">'
            f'{_format_remaining(remaining)}</div>',
            unsafe_allow_html=True,
        )

    def set_status(msg: str):
        status_placeholder.markdown(
            f'<div style="padding:4px 0; font-size:14px; color:#666; '
            f'font-style:italic;">{msg}</div>',
            unsafe_allow_html=True,
        )

    def log_step(label: str, detail: str = ""):
        completed_html_parts.append(_build_step_html(label, detail))
        log_placeholder.markdown(
            "\n".join(completed_html_parts),
            unsafe_allow_html=True,
        )

    try:
        # -- Step 1: Query Decomposition --
        update_time_remaining()
        set_status(STEP_DESCRIPTIONS["decomposition"])
        t0 = time.time()
        decomp_agent = get_decomposition_agent()
        decomposed = decomp_agent.run(context)
        elapsed_total += time.time() - t0
        progress_bar.progress(10)

        n_total = decomposed.total_queries()
        n_struct = len(decomposed.structured_data)
        n_docs = len(decomposed.document_rag)
        n_market = len(decomposed.market_intelligence)
        n_news = len(decomposed.news)
        log_step(
            "Meeting understood",
            f"{n_total} research questions across "
            f"database ({n_struct}), documents ({n_docs}), "
            f"market research ({n_market}), news ({n_news})",
        )

        # -- Step 2: Structured Data --
        update_time_remaining()
        set_status(STEP_DESCRIPTIONS["structured"])
        t0 = time.time()
        struct_agent = get_structured_agent()
        struct_result = struct_agent.run(
            questions=decomposed.structured_data,
            plan_name=context.plan_name,
            manager_name=context.manager_name,
        )
        elapsed_total += time.time() - t0
        progress_bar.progress(25)

        answered = sum(1 for a in struct_result.answers if not a.is_empty())
        unanswered = len(struct_result.answers) - answered
        detail = f"{answered} of {len(struct_result.answers)} database queries returned data"
        if unanswered:
            detail += f" ({unanswered} returned nothing)"
        log_step("Fund data retrieved", detail)

        # -- Step 3: Document RAG --
        update_time_remaining()
        set_status(STEP_DESCRIPTIONS["rag"])
        t0 = time.time()
        rag_agent = get_rag_agent()
        rag_result = rag_agent.run(
            questions=decomposed.document_rag,
            plan_name=context.plan_name,
        )
        elapsed_total += time.time() - t0
        progress_bar.progress(45)

        total_chunks = sum(len(r.chunks) for r in rag_result.question_results)
        n_signals = len(rag_result.topic_shift_signals)
        unique_sources = len({
            c.metadata.get("source_file", "")
            for r in rag_result.question_results
            for c in r.chunks
        })
        detail = f"{total_chunks} passages from {unique_sources} documents"
        if n_signals:
            topics = ", ".join(
                s.topic.replace("_", " ")
                for s in rag_result.topic_shift_signals[:3]
            )
            detail += f" -- board tone shifted on: {topics}"
        log_step("Documents read", detail)

        # -- Step 4: Market Intelligence --
        update_time_remaining()
        set_status(STEP_DESCRIPTIONS["market"])
        t0 = time.time()
        market_agent = get_market_agent()
        market_result = market_agent.run(
            questions=decomposed.market_intelligence,
            strategy=context.strategy,
        )
        elapsed_total += time.time() - t0
        progress_bar.progress(62)

        market_chunks = sum(len(r.chunks) for r in market_result.question_results)
        market_sources = list({
            c.metadata.get("source_file", "").replace(".pdf", "").replace("_", " ").title()
            for r in market_result.question_results
            for c in r.chunks
            if c.metadata.get("source_file")
        })
        log_step(
            "Market research reviewed",
            f"{market_chunks} passages from "
            f"{', '.join(market_sources) if market_sources else 'research documents'}",
        )

        # -- Step 5: News --
        update_time_remaining()
        set_status(STEP_DESCRIPTIONS["news"])
        t0 = time.time()
        news_agent = get_news_agent()
        news_result = news_agent.run(
            questions=decomposed.news,
            plan_name=context.plan_name,
            strategy=context.strategy,
        )
        elapsed_total += time.time() - t0
        progress_bar.progress(75)

        total_items = sum(len(r.items) for r in news_result.question_results)
        mode = (
            news_result.question_results[0].mode_used
            if news_result.question_results else "unknown"
        )
        news_sources = list({
            item.source
            for r in news_result.question_results
            for item in r.items
            if item.source
        })[:4]
        mode_label = "live search" if mode == "live" else "curated sources"
        log_step(
            "News gathered",
            f"{total_items} articles via {mode_label}"
            + (f" -- {', '.join(news_sources)}" if news_sources else ""),
        )

        # -- Step 6: Synthesis --
        update_time_remaining()
        set_status(STEP_DESCRIPTIONS["synthesis"])
        t0 = time.time()
        synth_agent = get_synthesis_agent()
        briefing_result = synth_agent.run(
            meeting_context=context,
            structured_result=struct_result,
            rag_result=rag_result,
            market_result=market_result,
            news_result=news_result,
            report_template=REPORT_TEMPLATE,
            output_path="./briefing_output.pdf",
        )
        elapsed_total += time.time() - t0
        progress_bar.progress(100)

        section_titles = [s.title for s in briefing_result.sections]
        log_step(
            "Briefing written",
            f"{len(section_titles)} sections: {', '.join(section_titles)}",
        )

        # Done: hide time estimate, update status
        time_placeholder.empty()
        status_placeholder.markdown(
            f'<div style="padding:12px 0; font-size:15px; font-weight:600; '
            f'color:{ACCENT};">Your briefing is ready.</div>',
            unsafe_allow_html=True,
        )

        # Store results
        st.session_state["briefing"] = briefing_result

        with open(briefing_result.html_path, "r", encoding="utf-8") as f:
            st.session_state["html_content"] = f.read()

        if briefing_result.pdf_path:
            try:
                with open(briefing_result.pdf_path, "rb") as f:
                    st.session_state["pdf_bytes"] = f.read()
            except Exception:
                st.session_state["pdf_bytes"] = None
        else:
            st.session_state["pdf_bytes"] = None

        render_disclaimer()

        # Auto-navigate to preview
        go_to("preview")
        st.rerun()

    except Exception as e:
        st.session_state["error"] = {
            "message": str(e),
            "traceback": traceback.format_exc(),
        }
        go_to("error")
        st.rerun()


# ---------------------------------------------------------------------------
# PAGE 3 - Briefing Preview
# ---------------------------------------------------------------------------

PREVIEW_CSS = f"""
<style>
    .briefing-cover {{
        background: linear-gradient(135deg, #1a1a2e 0%, #2d1b4e 60%, {ACCENT} 100%);
        color: white;
        padding: 48px 40px;
        border-radius: 8px;
        margin-bottom: 32px;
    }}
    .cover-label {{
        font-size: 10px;
        font-weight: 700;
        letter-spacing: 3px;
        text-transform: uppercase;
        color: {ACCENT_LIGHT};
        margin-bottom: 12px;
    }}
    .cover-title {{
        font-size: 36px;
        font-weight: 300;
        margin-bottom: 6px;
    }}
    .cover-subtitle {{
        font-size: 18px;
        color: #a8b2c1;
        margin-bottom: 28px;
    }}
    .cover-grid {{
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 16px;
        border-top: 1px solid rgba(255,255,255,0.15);
        padding-top: 20px;
    }}
    .cover-item label {{
        font-size: 9px;
        letter-spacing: 2px;
        text-transform: uppercase;
        color: {ACCENT_LIGHT};
        display: block;
        margin-bottom: 2px;
    }}
    .cover-item span {{
        font-size: 13px;
        color: #e8ecf0;
    }}
    .section-heading {{
        font-size: 18px;
        font-weight: 700;
        letter-spacing: 2px;
        text-transform: uppercase;
        color: {ACCENT};
        border-bottom: 2px solid {ACCENT};
        padding-bottom: 8px;
        margin-bottom: 16px;
        margin-top: 32px;
    }}
    .section-body p {{
        margin-bottom: 10px;
        line-height: 1.7;
    }}
    .section-meta {{
        font-size: 11px;
        color: #aab0bc;
        font-style: italic;
        margin-top: 12px;
    }}
    .insights-box {{
        background: {ACCENT_BG};
        border-left: 4px solid {ACCENT};
        border-radius: 0 8px 8px 0;
        padding: 28px 32px;
        margin-top: 16px;
    }}
    .insights-heading {{
        font-size: 18px;
        font-weight: 700;
        letter-spacing: 2px;
        text-transform: uppercase;
        color: {ACCENT};
        margin-bottom: 16px;
    }}
</style>
"""


def render_cover(meeting_context):
    from datetime import date as date_cls
    today = date_cls.today().strftime("%B %d, %Y")

    manager_block = ""
    if meeting_context.manager_name:
        manager_block = (
            f'<div class="cover-item"><label>Manager</label>'
            f'<span>{meeting_context.manager_name}</span></div>'
        )

    # Build as one contiguous string to avoid Streamlit splitting on newlines
    html = (
        PREVIEW_CSS
        + '<div class="briefing-cover">'
        + '<div class="cover-label">Confidential Meeting Preparation</div>'
        + '<div class="cover-title">Intelligence Briefing</div>'
        + f'<div class="cover-subtitle">{meeting_context.plan_name}</div>'
        + '<div class="cover-grid">'
        + f'<div class="cover-item"><label>Strategy</label><span>{meeting_context.strategy}</span></div>'
        + f'<div class="cover-item"><label>Meeting Type</label><span>{meeting_context.meeting_type}</span></div>'
        + f'<div class="cover-item"><label>Meeting Date</label><span>{meeting_context.meeting_date}</span></div>'
        + f'<div class="cover-item"><label>Prepared</label><span>{today}</span></div>'
        + manager_block
        + '</div>'   # close cover-grid
        + '</div>'   # close briefing-cover
    )

    st.markdown(html, unsafe_allow_html=True)


def render_section(section, index: int):
    st.markdown(f'<div id="section-{index}"></div>', unsafe_allow_html=True)
    st.markdown(
        f'<div class="section-heading">{section.title}</div>',
        unsafe_allow_html=True,
    )
    st.markdown(
        f'<div class="section-body">{section.content_html}</div>',
        unsafe_allow_html=True,
    )
    st.markdown(
        f'<div class="section-meta">Sources: {", ".join(section.data_sources_used)}</div>',
        unsafe_allow_html=True,
    )
    st.markdown("---")


def render_insights(insights_html: str):
    st.markdown('<div id="proactive-insights"></div>', unsafe_allow_html=True)
    html = (
        '<div class="insights-box">'
        '<div class="insights-heading">Proactive Insights</div>'
        + insights_html
        + '</div>'
    )
    st.markdown(html, unsafe_allow_html=True)


def page_preview():
    briefing = st.session_state.get("briefing")
    html_content = st.session_state.get("html_content")

    if not briefing or not html_content:
        go_to("input")
        st.rerun()
        return

    # Sidebar: TOC only
    with st.sidebar:
        st.markdown("### \U0001f52d Apollo View")
        st.markdown(f"**{briefing.meeting_context.plan_name}**")
        st.caption(
            f"{briefing.meeting_context.strategy} \u00b7 "
            f"{briefing.meeting_context.meeting_type}"
        )
        st.markdown("---")
        st.markdown("**Table of Contents**")
        for i, section in enumerate(briefing.sections):
            st.markdown(
                f'<a href="#section-{i}" style="text-decoration:none; color:{ACCENT};">'
                f'{i + 1}. {section.title}</a>',
                unsafe_allow_html=True,
            )
        st.markdown(
            f'<a href="#proactive-insights" style="text-decoration:none; color:{ACCENT};">'
            f'Proactive Insights</a>',
            unsafe_allow_html=True,
        )

    # Main content
    render_cover(briefing.meeting_context)

    for i, section in enumerate(briefing.sections):
        render_section(section, i)

    render_insights(briefing.proactive_insights_html)

    # Downloads and reset in main area so they're always visible
    st.markdown("---")
    btn_cols = st.columns(3)
    with btn_cols[0]:
        st.download_button(
            label="Download HTML",
            data=html_content,
            file_name="apollo_view_briefing.html",
            mime="text/html",
            use_container_width=True,
        )
    with btn_cols[1]:
        pdf_bytes = st.session_state.get("pdf_bytes")
        if pdf_bytes:
            st.download_button(
                label="Download PDF",
                data=pdf_bytes,
                file_name="apollo_view_briefing.pdf",
                mime="application/pdf",
                use_container_width=True,
            )
        else:
            st.button("PDF unavailable", disabled=True, use_container_width=True)
    with btn_cols[2]:
        if st.button("New Briefing", use_container_width=True):
            for key in ["input", "briefing", "html_content", "pdf_bytes"]:
                st.session_state.pop(key, None)
            go_to("input")
            st.rerun()

    render_disclaimer()


# ---------------------------------------------------------------------------
# PAGE 4 - Error
# ---------------------------------------------------------------------------

def page_error():
    st.title("\U0001f52d Apollo View")
    st.error("An error occurred while generating your briefing.")

    err = st.session_state.get("error", {})
    st.markdown(f"**Error:** {err.get('message', 'Unknown error')}")

    with st.expander("Full Traceback"):
        st.code(err.get("traceback", "No traceback available"), language="python")

    if st.button("Try Again", type="primary", use_container_width=True):
        st.session_state.pop("error", None)
        go_to("input")
        st.rerun()

    render_disclaimer()


# ---------------------------------------------------------------------------
# Router
# ---------------------------------------------------------------------------

if "page" not in st.session_state:
    st.session_state["page"] = "input"

page = st.session_state["page"]

if page == "input":
    page_input()
elif page == "progress":
    page_progress()
elif page == "preview":
    page_preview()
elif page == "error":
    page_error()
else:
    go_to("input")
    st.rerun()